import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {chromium} from 'playwright';
const project='https://oms-qa.supabase.co',uid='11111111-1111-4111-8111-111111111111';
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5188','--strictPort'],{cwd:process.cwd(),env:{...process.env,VITE_SUPABASE_URL:project,VITE_SUPABASE_ANON_KEY:'mock-public-key',VITE_AUTHORIZED_UID:uid},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(b.toString().includes('Local:'))resolve()});server.on('exit',c=>reject(Error('Server exited '+c)));});
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process','--use-gl=disabled','--disable-software-rasterizer'],headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message)});page.setDefaultTimeout(12000);
 const authUser={id:uid,email:'qa@example.com',aud:'authenticated',role:'authenticated'};
 const collections={oms_orders:[{id:'o1',orderId:'O1',sku:'SKU',company:'Company A',channel:'Amazon',quantity:2,status:'Return Received',dispatchedAt:new Date().toISOString(),createdAt:new Date().toISOString(),courier:'Amazon Shipping'},{id:'o2',orderId:'O2',sku:'SKU',company:'Company B',channel:'Meesho',quantity:1,status:'Ready to Ship',createdAt:new Date().toISOString(),courier:'Shadowfax'}],oms_products:[{id:'p',sku:'SKU',rate:100,stockQuantity:0}],oms_payments:[{id:'pay',orderId:'O1',settlement:235,netAmount:235,gstAmount:0,transactions:[{id:'t',amount:235}]}],oms_trash:[],oms_fraud_list:[],oms_business_records:[]};
 await page.route('https://oms-qa.supabase.co/**',async r=>{const url=new URL(r.request().url());let body={};if(url.pathname.includes('/token'))body={access_token:'mock-token',refresh_token:'mock-refresh',expires_in:3600,token_type:'bearer',user:authUser};else if(url.pathname.endsWith('/user'))body=authUser;else if(url.pathname.includes('/rest/')){const table=url.pathname.split('/').at(-1);if(r.request().method()==='POST'){for(const row of r.request().postDataJSON()){collections[table]||=[];collections[table]=collections[table].filter(x=>x.id!==row.id);collections[table].push(row.data);}body=[];}else body=(collections[table]||[]).map(data=>({id:data.id,data}));}await r.fulfill({json:body});});
 await page.goto('http://127.0.0.1:5188');await page.getByLabel('Email',{exact:true}).fill('qa@example.com');await page.getByLabel('Password',{exact:true}).fill('mock');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.nav-item').first().waitFor();
 const nav=async s=>page.locator('.nav-item').filter({hasText:s}).first().click();
 await nav('Pickup Dashboard');await page.waitForTimeout(250);assert.ok((await page.locator('.content').innerText()).includes('Pickup'));
 await nav('Business Workspace');assert.ok(await page.locator('img.supplied-logo').isVisible());const tab=async s=>page.locator('.business-tabs').getByRole('button',{name:s,exact:true}).click();
 const fill=async(name,value)=>page.getByLabel(name,{exact:true}).fill(value);const choose=async(name,value)=>page.getByLabel(name,{exact:true}).selectOption(value);
 await tab('Inventory');await page.locator('select[name=productId]').first().selectOption('p');await fill('Sellable quantity','10');await fill('Count reason','Opening count');await page.locator('.business-form').first().getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.business-hub table')?.textContent.includes('Active'));
 await tab('Purchases');await choose('SKU','p');for(const [k,v] of [['Supplier','Supplier A'],['Supplier invoice / reference','INV-1'],['Accepted sellable quantity','4'],['Rejected quantity','1'],['Unit cost','95'],['Ordered date','2026-09-20'],['Promised date','2026-09-25'],['Received date','2026-09-27']])await fill(k,v);await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'INV-1',exact:true}).waitFor();
 await tab('Return QC');await choose('Received order','O1');await fill('Good quantity','1');await fill('Damaged / wrong / missing quantity','1');await choose('Condition','Mixed');await fill('Actual item loss ₹ (not return charge)','100');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'Mixed',exact:true}).waitFor();
 await tab('Inventory');let cells=await page.locator('tbody tr').first().locator('td').allTextContents();assert.equal(cells[2],'15');assert.equal(cells[4],'14');assert.equal(cells[5],'1');
 await tab('Claims');await fill('Order ID','O1');await fill('Reason: wrong product / damage / missing','Wrong product');await fill('Requested ₹','400');await fill('Received ₹ to date','50');await fill('Submission / follow-up deadline','2026-09-27');await choose('Status','Part paid');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'₹350.00',exact:true}).last().waitFor();await page.getByLabel('Claim company',{exact:true}).selectOption('Company A');assert.ok((await page.locator('.business-hub table').first().innerText()).includes('Company A'));await page.getByLabel('Claim calendar date',{exact:true}).fill('2026-09-27');await page.getByRole('button',{name:'Edit',exact:true}).click();await fill('Received ₹ to date','400');await choose('Status','Paid');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'Paid',exact:true}).waitFor();
 await tab('Expenses');await choose('Company','Company A');await choose('Category','Packing');await fill('Date','2026-09-27');await fill('Amount ₹','10');await fill('Unique bill / reference','PACK-1');await fill('Description','Packing');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'PACK-1',exact:true}).waitFor();
 await tab('Attendance');await fill('Employee name / ID','Employee 1');await fill('Date','2026-09-27');await choose('Attendance','Present');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'Employee 1',exact:true}).waitFor();
 await tab('Bank');await fill('Bank UTR / unique reference','UTR-1');await fill('Bank date','2026-09-27');await fill('Order IDs, comma separated','O1');await fill('Bank credit ₹','234');await page.locator('.business-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('cell',{name:'₹-1.00',exact:true}).waitFor();
 await tab('Backup');await page.getByRole('button',{name:'Save local checkpoint',exact:true}).click();await page.getByRole('cell',{name:'manual',exact:true}).waitFor();const file=page.waitForEvent('download');await page.getByRole('button',{name:'Download full JSON',exact:true}).click();const dl=await file;await dl.saveAs('qa/business-qa-backup.json');const saved=JSON.parse(fs.readFileSync('qa/business-qa-backup.json'));assert.equal(saved.data.payments[0].transactions.length,1);assert.equal(saved.data.orders.find(o=>o.id==='o1').manualLoss,100);assert.equal(saved.data.businessRecords.filter(r=>r.kind==='claim').length,1);assert.equal(saved.data.businessRecords.find(r=>r.kind==='claim').received,400);
 await tab('Today');assert.ok((await page.locator('.business-hub').innerText()).includes('₹125.00'));await page.waitForTimeout(3800);await page.screenshot({path:'qa/business-workspace-preview.png',fullPage:true});
 await page.waitForTimeout(1800);assert.ok(collections.oms_business_records.length>=7);await page.reload();await nav('Business Workspace');await tab('Inventory');assert.equal((await page.locator('tbody tr').first().locator('td').allTextContents())[2],'15');assert.deepEqual(errors,[]);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(450);assert.ok((await page.locator('.sidebar').boundingBox()).x+240<=0);await page.screenshot({path:'qa/business-mobile-preview.png',fullPage:true});
 const report={status:'PASS',scope:'Local browser with mocked Supabase, no live database access',checks:['Authenticated app loads','Pickup return-history rendering','Opening stock 10 + purchase 4 + inspected good return 1 = 15','Reserved 1 gives available 14','Damaged stock 1','QC manual loss 100 recorded once','Claim create/edit 50 then 400, no profit duplication','Packing expense 10 and final profit 125','Attendance','Bank difference -1','JSON nested backup','Business records synced to mock and survive reload'],runtimeErrors:errors};fs.writeFileSync('tests/browser-results.json',JSON.stringify(report,null,2));console.log(report);
}catch(e){console.error(e);throw e;}finally{await browser.close();server.kill();}
