-- LIVE SETUP for project pgctafxsbcvrbqbqkzer (UID already filled in).
-- Supabase > SQL Editor > paste all > Run. Deletes NO data.
-- It adds any missing table (e.g. oms_business_records) and locks every OMS table
-- to lavanayaaarimaterials@gmail.com only. After this the OLD app stops working
-- (it has no login) - run it when you switch to the new site.
DO $$
DECLARE
  owner uuid := 'eb0e75f2-f376-4b66-9d90-c5db292158b3';
  t text; p record;
BEGIN
  -- main OMS tables (id + JSON data)
  FOREACH t IN ARRAY ARRAY['oms_orders','oms_payments','oms_products','oms_trash',
      'oms_fraud_list','oms_business_records'] LOOP
    EXECUTE format('CREATE TABLE IF NOT EXISTS public.%I (
      id text PRIMARY KEY,
      data jsonb NOT NULL DEFAULT ''{}''::jsonb,
      updated_at timestamptz NOT NULL DEFAULT now())', t);
  END LOOP;

  -- repeat-returner / fraud history
  CREATE TABLE IF NOT EXISTS public.customer_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lookup_key text UNIQUE NOT NULL,
    customer_name text DEFAULT '', phone text DEFAULT '', address text DEFAULT '',
    company_id text DEFAULT 'unknown', channel text DEFAULT '', last_order_id text DEFAULT '',
    order_count integer NOT NULL DEFAULT 0, return_count integer NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now());

  -- daily pickup snapshots
  CREATE TABLE IF NOT EXISTS public.oms_reconciliation_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date date UNIQUE NOT NULL,
    summary_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    saved_at timestamptz NOT NULL DEFAULT now());

  CREATE INDEX IF NOT EXISTS oms_orders_status_idx ON public.oms_orders ((data->>'status'));

  -- lock every table to the one owner login
  FOREACH t IN ARRAY ARRAY['oms_orders','oms_payments','oms_products','oms_trash','oms_fraud_list',
      'oms_business_records','customer_profiles','oms_reconciliation_history'] LOOP
    FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=t LOOP
      EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, t);
    END LOOP;
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('CREATE POLICY oms_owner ON public.%I FOR ALL TO authenticated USING ((select auth.uid()) = %L::uuid) WITH CHECK ((select auth.uid()) = %L::uuid)', t, owner, owner);
  END LOOP;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

  -- live refresh between computers
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['oms_orders','oms_payments','oms_products','oms_trash',
        'oms_fraud_list','oms_business_records'] LOOP
      IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime'
                     AND schemaname='public' AND tablename=t) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
  RAISE NOTICE 'OMS database ready (8 tables, locked to owner).';
END $$;
